#!/bin/sh
set -ue

allow_regexp="$( git config --get "$CONFIG_NAMESPACE.allow-regexp" || : )"

if [ -z "$allow_regexp" ]
then
    return
fi

remote_branch="$( echo "$REMOTE_REF" | sed 's~refs/heads/~~' )"
if echo "$remote_branch" | grep -qE '^(master|main|development|staging|production)$'
then
    return
fi

main_branch="$( git symbolic-ref "refs/remotes/$REMOTE/HEAD" | sed 's~refs/remotes/[^\/]*/~~' )"
if [ "$remote_branch" = "$main_branch" ]
then
    return
fi

if ! echo "$remote_branch" | grep -qE "$allow_regexp"
then
    error "Branch name does not conform to configured pattern: %s" "$allow_regexp"
    exit 1
fi
