#!/usr/bin/env sh
set -ue

# TODO Skip for Merge commits

if [ -n "$RANGE" ]
then
    regex='\<(WIP|TODO)\>'
    if
        git diff --pickaxe-regex -S "$regex" "$RANGE" | grep -E "^\\+ .*$regex"
    then
        error 'Found changes introducing WIP|TODO. Resolve before pushing.'
        false
    fi
fi
