#!/bin/sh
set -ue

# TODO Skip for '^(Merge|Revert|fixup!|squash!) '
# TODO Only follow first parent? (skip merges)

if [ -n "$RANGE" ]
then
    commit="$(
        git rev-list -E --grep '\<(WIP|TODO)\>' --format="%B" "$RANGE"
    )"
    if [ -n "$commit" ]
    then
        error "Found WIP|TODO commit(s) in %s, not pushing:\n%s" "$LOCAL_REF" "$commit"
        exit 1
    fi
fi
