#!/bin/sh
set -e

if [ -n "$RANGE" ]
then
    # Check for WIP commit
    commit="$( git rev-list -n 1 --grep '^WIP' "$RANGE" )"
    if [ -n "$commit" ]
    then
        echo >&2 "Found WIP commit in $LOCAL_REF, not pushing"
        exit 1
    fi
fi
