#!/bin/sh
set -e

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if [ -n "$RANGE" ]
then
    if command -v eslint >/dev/null && eslint --print-config dummy.js >/dev/null 2>&1
    then
        # FIXME Check if files exist
        # TODO Run single instance for files without local changes
        # TODO Re–use code from pre-commit. When ready, run other linters as well
        # We are disabling import/no-unused-modules, because it increases linting time significantly
        total="$( git diff --name-only "$RANGE" -- '*.js' '*.mjs' '*.jsx' '*.ts' '*.tsx' | wc -l )"
        git diff --name-only "$RANGE" -- '*.js' '*.mjs' '*.jsx' '*.ts' '*.tsx' |
            nl |
            while read -r number file
            do
                printf "%d/%d: " "$number" "$total" 1>&2
                git show :"$file" | {
                    set -"$shopt"
                    eslint --rule='import/no-unused-modules:0' --stdin --stdin-filename="$file"
                }
            done
    fi
fi
