#!/bin/sh
set -e

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if [ -n "$RANGE" ]
then
    if command -v eslint >/dev/null && eslint --print-config dummy.js >/dev/null 2>&1
    then
        # FIXME Check if files exist
        # TODO Run single instance for files without local changes
        # TODO Re–use code from pre-commit. When ready, run other linters as well
        git diff --name-only "$RANGE" -- '*.js' '*.mjs' '*.jsx' '*.ts' '*.tsx' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; eslint --stdin --stdin-filename=\"\$1\"; }" --
    fi
fi
