#!/usr/bin/env sh
set -ue

# FIXME Use $RANGE

if
    [ -n "$RANGE" ] &&
    [ -r package.json ] &&
    command -v npm >/dev/null
then
    if [ "$VERBOSITY" -ge 6 ]
    then
        shopt="x"
    else
        shopt=
    fi

    if [ -r yarn.lock ]
    then
        if command -v yarn >/dev/null
        then
            if [ "$(yarn --version | cut -d. -f1)" -ge "2" ]
            then
                sh -"$shopt$-" -c "yarn install --check-resolutions --json 2>/dev/null | jq -r 'select(.type==\"error\") | \"\\(.displayName): \\(.data)\" | empty // halt_error(1)'"
            else
                sh -"$shopt$-" -c "yarn check --verify-tree"
            fi
        fi
    elif command -v npm >/dev/null
    then
        if sh -"$shopt$-" -c 'npm ls --depth=1 2>&1 | grep "^npm error " 1>&2'
        then
            exit 1
        fi
    fi
fi
