#!/bin/sh
set -ue

# TODO Lock switching branches while this hook is working
# TODO On Ctrl-C ask if one wants to continue

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
    npm_run_args=
else
    shopt=
    npm_run_args="--silent"
fi

uses_jest ()
{
    if echo "$test_script" | grep -Eq '\b(jest|(react-scripts|craco)[[:space:]]+test)\b'
    then
        return 0
    fi

    if echo "$test_script" | grep -Eq '^[[:space:]]*node([[:space:]]+-[^[:space:]]+)*[[:space:]][^[:space:]]+$'
    then
        script="$( echo "$test_script" | grep -Eo '[^[:space:]]+$' )"
        grep -q '\<jest\>' "$script"
        return $?
    fi

    return 1
}

if [ -n "$RANGE" ] && ! git diff --quiet "$RANGE" -- \
    ':(exclude,icase)./docs/' ':(exclude,icase)./documentation/' \
    ':(exclude,icase)README' ':(exclude,icase)README.md'
then
    # TODO This should be a globa thing
    # TODO Auto–cleanup on next run (keep a pidfile)
    workspace_enabled_config="$GLOBAL_CONFIG_NAMESPACE.tmpWorkspace"
    workspace_enabled="$( git config --get "$workspace_enabled_config" || echo false )"
    if [ "$workspace_enabled" = "true" ]
    then
        mode=tmp_worktree
        # TODO Handle names with spaces
        workspace_files="$( git status --short --ignored | grep '^!! ' | cut -b4- | sed 's~/$~~' )"
        pwd_basename="$( basename "$PWD" )"
        tmp_worktree="$( mktemp -d "git-hook-${pwd_basename}-XXXXXXXXXX" )"
        set +e
        git worktree add --detach "$tmp_worktree"
        exit_status=$?
        set -e
        if [ "$exit_status" != 0 ]
        then
            return "$exit_status"
        fi
        cd "$tmp_worktree"
        if [ -n "$workspace_files" ]
        then
            # TODO Register a trap to remove the worktree
            echo "$workspace_files" |
                while read -r target
                do
                    if [ -e "$OLDPWD/$target" ]
                    then
                        mkdir -p "$( dirname "$target" )"
                        ln -sv "$OLDPWD/$target" "$target"
                    fi
                done
        fi
    elif git diff --quiet
    then
        mode=
    else
        mode=stashed
        git stash --keep-index --message="Stashed for running tests"
    fi

    start="$( date +%s )"
    test_script="$( npm run | grep -A1 '^  test$' | tail -n+2 )"
    set +e
    if uses_jest "$test_script"
    then
        # TODO Use --changedSince if forcedFiles is not set
        # TODO If list is too long, fall–back to running all tests
        {
            git config --get "$CONFIG_NAMESPACE.forcedFiles" || :
            git diff --name-only "$RANGE"
        } | xargs "$SHELL" -$-"$shopt"c "npm test $npm_run_args -- --ci --color --coverage=no --passWithNoTests --findRelatedTests \"\$@\"" _
    else
        npm test $npm_run_args
    fi
    test_exit_code=$?
    set -e
    if [ "$mode" != "tmp_worktree" ]
    then
        end="$( date +%s )"
        time="$(( end - start ))"
        if [ "$time" -gt 5 ]
        then
            # TODO Don’t printf directly
            printf "Your tests take a while to finish. You might be interested in enabling temporary worktree so that you can continue working (switch branches, commit etc.) while tests run.\n"
            printf "    git config %s true\n" "$workspace_enabled_config"
        fi
    fi

    if [ "$mode" = "tmp_worktree" ]
    then
        cd - >/dev/null
        if git worktree 2>&1 | grep -q 'worktree remove'
        then
            git worktree remove -f "$tmp_worktree"
        else
            rm -rf "$tmp_worktree"
        fi
    elif [ "$mode" = "stashed" ]
    then
        git stash pop
    fi

    if [ "$test_exit_code" != "0" ]
    then
        return "$test_exit_code"
    fi
fi
