#!/bin/sh
set -e

allownonascii="$( git config --bool hooks.allownonascii || : )"

count_invalid_names ()
{
    # Note that the use of brackets around a tr range is ok here, (it's
    # even required, for portability to Solaris 10's /usr/bin/tr), since
    # the square bracket bytes happen to fall in the designated range.
    git diff --cached --name-only --diff-filter=A -z "$AGAINST" |
        LC_ALL=C tr -d '[ -~]\0' |
        wc -c
}

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] && [ "$( count_invalid_names )" != 0 ]
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
    false
fi
