#!/bin/sh
set -ue

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if [ -n "$AGAINST" ]
then
    if command -v eslint >/dev/null && eslint --print-config dummy.js >/dev/null 2>&1
    then
        set -- ':(icase)*.js' ':(icase)*.mjs' ':(icase)*.cjs' ':(icase)*.jsx' ':(icase)*.ts' ':(icase)*.tsx'

        # Don’t use --cached when AGAINST is a range (i.e. we are running pre-push hook)
        # TODO Duplicated for all lint-* pre-commit hooks
        if echo "$AGAINST" | grep -q -F ".."
        then
            diff_opt=
        else
            diff_opt="--cached"
        fi

        if git diff --quiet -- "$@"
        then
            # No unstaged modifications -- running eslint on files

            git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" -- "$@" |
                xargs sh -$-"${shopt}" -c "eslint --rule='import/no-unused-modules:0' \"\$@\"" --
        else
            # Some staged modifications -- running eslint on staged diffs

            # TODO Run git-diff once?
            # FIXME Check if files exist
            # TODO When running one–by–one run all and report all broken at the end

            # We are disabling import/no-unused-modules, because it increases linting time significantly
            total="$(
                git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" -- "$@" \
                    | wc -l
            )"
            if [ "$total" -gt 0 ]
            then
                secondary "Running eslint on %d files." "$total"

                # We are disabling import/no-unused-modules, because it increases linting time significantly
                git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" -- "$@" |
                    nl |
                    while read -r number file
                    do
                        printf "%d/%d: " "$number" "$total" 1>&2
                        git show :"$file" | {
                            set -"$shopt"
                            eslint --rule='import/no-unused-modules:0' --stdin --stdin-filename="$file"
                        }
                    done
            fi
        fi
    fi
fi
