#!/bin/sh
set -ue

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -ge 7 ]
then
    shopt=x
else
    shopt=
fi

if [ -n "$AGAINST" ]
then
    if command -v stylelint >/dev/null && stylelint --print-config dummy.css >/dev/null 2>&1
    then
        # Don’t use --cached when AGAINST is a range (i.e. we are running pre-push hook)
        # TODO Duplicated for all lint-* pre-commit hooks
        if echo "$AGAINST" | grep -q -F ".."
        then
            diff_opt=
        else
            diff_opt="--cached"
        fi

        # TODO Run git-diff once?
        css_total=$(( $(
            git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" ':(icase)*.css' \
                | wc -l
        ) ))
        scss_total=$(( $(
            git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" ':(icase)*.scss' \
                | wc -l
        ) ))
        total=$(( css_total + scss_total ))

        if [ "$total" -gt 0 ]
        then
            secondary "Running stylelint on %d files." "$total"

            # TODO Run single instance for files without local changes
            git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" ':(icase)*.css' |
                nl |
                while read -r number file
                do
                    printf "%d/%d: " "$number" "$total" 1>&2
                    git show :"$file" | {
                        set -"$shopt"
                        stylelint --stdin-filename="$file"
                    }
                done

            if [ "$scss_total" -gt 0 ]
            then
                if stylelint --help | grep -q -- --syntax
                then
                    # Legacy
                    scss_arg="echo --syntax=scss"
                else
                    postcss_plugin="$( npm ls --depth=0 --parseable postcss-scss )"
                    if [ -z "$postcss_plugin" ]
                    then
                        warning 2>&1 'Install postcss-scss npm package to lint SCSS files.'
                    fi
                    scss_arg="--custom-syntax='$postcss_plugin'"
                fi

                git diff $diff_opt --diff-filter=ACMR --name-only "$AGAINST" ':(icase)*.scss' |
                    nl -v$(( css_total + 1 )) |
                    while read -r number file
                    do
                        printf "%d/%d: " "$number" "$total" 1>&2
                        git show :"$file" | {
                            set -"$shopt"
                            stylelint --stdin-filename="$file" "$scss_arg"
                        }
                    done
            fi
        fi
    fi
fi
