#!/bin/sh
set -e

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if command -v shellcheck >/dev/null 2>&1
then
    # FIXME | sed 's~/dev/stdin/~$1~', but without loosing exit code
    git diff --cached --diff-filter=ACMR --name-only "$AGAINST" |
        grep -E '^(.*/)?([^/.]+|[^/]+\.sh)$' |
        $XARGS grep -El '^#!/bin/(sh|bash|dash|ksh)' |
        $XARGS -n1 "$SHELL" -$-c "set -$shopt; git show :\"\$1\" | shellcheck /dev/stdin #" --
fi
