#!/bin/sh
set -e

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if command -v stylelint >/dev/null && stylelint --print-config dummy.css >/dev/null 2>&1
then
    # TODO Run git-diff once?
    count="$(
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" '*.css' '*.scss' \
            | wc -l
    )"
    if [ "$count" -gt 0 ]
    then
        secondary "Running stylelint on %d files." "$count"

        # TODO Run single instance for files without local changes
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" '*.css' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; stylelint --stdin-filename=\"\$1\"; }" --
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" '*.scss' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; stylelint --stdin-filename=\"\$1\" --syntax=scss; }" --
    fi
fi
