#!/bin/sh
set -e

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if command -v eslint >/dev/null && eslint --print-config dummy.js >/dev/null 2>&1
then
    # TODO Run git-diff once?
    count="$(
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" -- '*.js' '*.mjs' '*.jsx' '*.ts' '*.tsx' \
            | wc -l
    )"
    if [ "$count" -gt 0 ]
    then
        secondary "Running eslint on %d files." "$count"

        # TODO Run single eslint instance for files without local changes
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" -- '*.js' '*.mjs' '*.jsx' '*.ts' '*.tsx' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; eslint --stdin --stdin-filename=\"\$1\"; }" --
    fi
fi
