#!/bin/sh
set -e

# TODO Introduce $CONFIG_NAMESPACE.exclude

if [ "$VERBOSITY" -gt 1 ]
then
    shopt=x
else
    shopt=
fi

if command -v stylelint >/dev/null
then
    if stylelint --print-config dummy.css >/dev/null 2>&1
    then
        # TODO Run single instance for files without local changes
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" '*.css' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; stylelint --stdin-filename=\"\$1\"; }" --
        git diff --cached --diff-filter=ACMR --name-only "$AGAINST" '*.scss' |
            $XARGS -n1 "$SHELL" -$-c "git show :\"\$1\" | { set -$shopt; stylelint --stdin-filename=\"\$1\" --syntax=scss; }" --
    fi
fi
