#!/usr/bin/env sh
set -ue

# `act` is quite a generic name. Detect if it’s what we expect it to be
# by matching the help text

act_bin=
if act --help 2>&1 | grep -q 'Run GitHub actions locally'
then
    act_bin="act"
elif gh act --help >/dev/null 2>&1
then
    act_bin="gh act"
fi

if ! [ -z "$act_bin" ] && ! git diff "$AGAINST" --quiet -- ./.github/workflows
then
    (
        if [ "$VERBOSITY" -ge 7 ]
        then
            set -x
        fi

        $act_bin --dryrun --detect-event
    )
fi
