#!/bin/sh
set -ue

if [ -z "$IS_BRANCH_SWITCH" ]
then
    return
fi

# FIXME Don’t run during rebase
# TODO Also post-rebase and post-merge

if ! [ -d "./node_modules" ]
then
    return
fi

if [ -e ./yarn.lock ] && ! git diff --quiet "$PREV_REF..$NEW_REF" ./yarn.lock
then
    yarn install --silent --pure-lockfile
    "$PACKAGE_DIR/install.sh"
elif [ -e ./package-lock.json ] && ! git diff --quiet "$PREV_REF..$NEW_REF" ./package-lock.json
then
    npm install --save=false
    "$PACKAGE_DIR/install.sh"
fi
