#!/usr/bin/env sh
set -ue

if [ -z "$HOOKS_DIR" ]
then
    echo 1>&2 "ERROR: HOOKS_DIR is not set. Please re–install @saji/git-hooks."
    exit 64 # EX_USAGE
fi

# shellcheck disable=SC1091
. "$HOOKS_DIR/lib/bootstrap"

REMOTE="$1"
URL="$2"

while read -r LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA REST
do
    if [ "$REMOTE_SHA" != "$NULL_REF" ]
    then
        if [ "$( git cat-file -t "$REMOTE_SHA" 2>/dev/null )" != "commit" ]
        then
            error "Remote commit %s is not available locally. Try fetching first." "$REMOTE_SHA" 1>&2
            exit 65
        fi
    fi

    if [ "$LOCAL_SHA" = "$NULL_REF" ]
    then
        # Handle delete
        ACTION=delete
        RANGE=
    else
        ACTION=push
        if [ "$REMOTE_SHA" = "$NULL_REF" ]
        then
            # New branch, examine everything from base branch
            RANGE="$( git merge-base "$LOCAL_SHA" "$BASE_BRANCH@{u}" )..$LOCAL_SHA"
        else
            # Update to existing branch, examine new commits
            RANGE="$REMOTE_SHA..$LOCAL_SHA"
        fi
    fi

    export REMOTE URL
    export LOCAL_REF LOCAL_SHA REMOTE_REF REMOTE_SHA
    export ACTION RANGE

    run_hooks
done
